doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        server_version: '8.0' # Version de MySQL (ajustez selon votre version réelle)
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            enum: App\DBAL\EnumType
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App